import fs from 'node:fs/promises';
import path from 'node:path';

const VERSION='GFTSH-V1.9.0-GLOBAL-FUTURES-ACTIVE-TRADER-HUNTER';
const STATE_FILE=process.env.GLOBAL_STATE_FILE||'state/global_futures_hunter.json';
const CACHE_FILE=process.env.GLOBAL_CACHE_FILE||'state/global_futures_cache.json';
const TELEGRAM_TOKEN=process.env.TELEGRAM_TOKEN||'';
const TELEGRAM_CHAT_ID=process.env.TELEGRAM_CHAT_ID||'';
const LOOKBACK_MS=7*86400000;
const DISCOVERY_LIMIT=Number(process.env.GFTSH_DISCOVERY_LIMIT||400);
const HL_AUDIT_LIMIT=Number(process.env.GFTSH_HL_AUDIT_LIMIT||100);
const HL_ROTATION_BUCKETS=Number(process.env.GFTSH_HL_ROTATION_BUCKETS||4);
const HL_SIGNAL_LIMIT=Number(process.env.GFTSH_HL_SIGNAL_LIMIT||20);
const VERIFY_CONCURRENCY=Number(process.env.GFTSH_VERIFY_CONCURRENCY||4);
const VERIFY_TIMEOUT_MS=Number(process.env.GFTSH_VERIFY_TIMEOUT_MS||8500);
const TOP_SIGNALS=Number(process.env.GFTSH_TOP_SIGNALS||10);
const FRESH_MIN=Number(process.env.GFTSH_FRESH_MIN||15);
const ENTRY_MAX=Number(process.env.GFTSH_ENTRY_MAX_PCT||0.5);
const MIN_RR=Number(process.env.GFTSH_MIN_RR||1.5);
const MODEL_SL_PCT=Number(process.env.GFTSH_MODEL_SL_PCT||0.5);
const MODEL_TP_R=Number(process.env.GFTSH_MODEL_TP_R||2);
const MIN_TRADES=Number(process.env.GFTSH_MIN_7D_TRADES||40);
const MIN_DAYS=Number(process.env.GFTSH_MIN_ACTIVE_DAYS||5);
const MIN_WR=Number(process.env.GFTSH_MIN_WR||58);
const MIN_PF=Number(process.env.GFTSH_MIN_PF||1.8);
const MIN_DAILY_TRADES=Number(process.env.GFTSH_MIN_AVG_DAILY_TRADES||4);
const MAX_MEDIAN_H=Number(process.env.GFTSH_MAX_MEDIAN_HOURS||6);
const MAX_AVG_H=Number(process.env.GFTSH_MAX_AVG_HOURS||12);
const MAX_DD=Number(process.env.GFTSH_MAX_DD||30);
const HTTP_TIMEOUT=Number(process.env.GFTSH_HTTP_TIMEOUT_MS||8500);
const HL_REQ_GAP_MS=Number(process.env.GFTSH_HL_REQ_GAP_MS||180);
const OKX_REQ_GAP_MS=Number(process.env.GFTSH_OKX_REQ_GAP_MS||700);
const MAX_RETRIES=Number(process.env.GFTSH_MAX_RETRIES||1);
const CACHE_TTL_H=Number(process.env.GFTSH_DISCOVERY_CACHE_HOURS||12);
const UA='Mozilla/5.0 (compatible; GFTSH/1.9; +https://github.com/)' ;
let HL_NEXT_REQ=0,OKX_NEXT_REQ=0;

const VENUES={
 HYPERLIQUID:{label:'HYPERLIQUID',kind:'DEX',cap:'FULL_SIGNAL'},
 BINANCE:{label:'BINANCE',kind:'CEX',cap:'DISCOVERY'},
 OKX:{label:'OKX',kind:'CEX',cap:'DISCOVERY'},
 BYBIT:{label:'BYBIT',kind:'CEX',cap:'DISCOVERY'},
 BITGET:{label:'BITGET',kind:'CEX',cap:'DISCOVERY'},
 KUCOIN:{label:'KUCOIN',kind:'CEX',cap:'UNSUPPORTED'},GATE:{label:'GATE',kind:'CEX',cap:'UNSUPPORTED'},
 MEXC:{label:'MEXC',kind:'CEX',cap:'UNSUPPORTED'},PHEMEX:{label:'PHEMEX',kind:'CEX',cap:'UNSUPPORTED'},
 BINGX:{label:'BINGX',kind:'CEX',cap:'UNSUPPORTED'},COINEX:{label:'COINEX',kind:'CEX',cap:'UNSUPPORTED'},
 DYDX:{label:'DYDX',kind:'DEX',cap:'UNSUPPORTED'},PARADEX:{label:'PARADEX',kind:'DEX',cap:'UNSUPPORTED'}
};
function n(v,d=NaN){const x=Number(v);return Number.isFinite(x)?x:d} function ok(v){return Number.isFinite(n(v))}
function pct(v,d=2){return ok(v)?`${n(v).toFixed(d)}%`:'—'} function trunc(s,nc=18){s=String(s??'');return s.length>nc?s.slice(0,Math.ceil(nc/2))+'…'+s.slice(-Math.floor(nc/2)):s}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function ensure(){await fs.mkdir(path.dirname(STATE_FILE),{recursive:true});await fs.mkdir(path.dirname(CACHE_FILE),{recursive:true})}
async function readJson(f,d){try{return JSON.parse(await fs.readFile(f,'utf8'))}catch{return d}} async function writeJson(f,x){await fs.writeFile(f,JSON.stringify(x,null,2))}
async function rateGate(kind,gap){const now=Date.now();const next=kind==='HL'?HL_NEXT_REQ:OKX_NEXT_REQ;const wait=Math.max(0,next-now);if(wait)await sleep(wait);const stamp=Date.now()+gap;if(kind==='HL')HL_NEXT_REQ=stamp;else OKX_NEXT_REQ=stamp}
async function fetchTextRetry(url,opts={},kind='GEN'){let last='';for(let i=0;i<=MAX_RETRIES;i++){try{if(kind==='HL')await rateGate('HL',HL_REQ_GAP_MS);if(kind==='OKX')await rateGate('OKX',OKX_REQ_GAP_MS);const c=new AbortController(),timer=setTimeout(()=>c.abort(),HTTP_TIMEOUT);try{const r=await fetch(url,{...opts,signal:c.signal,headers:{accept:'application/json,text/html,*/*','user-agent':UA,...(opts.headers||{})}});const text=await r.text();if(r.ok)return text;last=`HTTP_${r.status}:${text.slice(0,220)}`;const retry=[408,425,429,500,502,503,504].includes(r.status);if(!retry||i>=MAX_RETRIES)throw new Error(last);await sleep(350*(i+1));}finally{clearTimeout(timer)}}catch(e){last=String(e.message||e);if(i>=MAX_RETRIES)throw new Error(last);await sleep(350*(i+1))}}throw new Error(last||'REQUEST_FAILED')}
async function json(url,opts={}){const kind=url.includes('hyperliquid.xyz')?'HL':url.includes('okx.com/api/')?'OKX':'GEN';const t=await fetchTextRetry(url,opts,kind);let x;try{x=JSON.parse(t)}catch{throw new Error(`NON_JSON:${t.slice(0,180)}`)}if(x&&x.code&&String(x.code)!=='0')throw new Error(`API_${x.code}:${x.msg||'API_ERROR'}`);return x}
async function postJson(url,body){const t=await fetchTextRetry(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)},url.includes('hyperliquid.xyz')?'HL':'GEN');try{return JSON.parse(t)}catch{throw new Error(`NON_JSON:${t.slice(0,180)}`)}}
function arr(x){if(Array.isArray(x))return x;if(Array.isArray(x?.leaderboardRows))return x.leaderboardRows;if(Array.isArray(x?.data?.ranks))return x.data.ranks;if(Array.isArray(x?.data?.list))return x.data.list;if(Array.isArray(x?.data?.rows))return x.data.rows;if(Array.isArray(x?.data))return x.data.flatMap(v=>Array.isArray(v?.ranks)?v.ranks:Array.isArray(v?.list)?v.list:Array.isArray(v?.rows)?v.rows:(v&&typeof v==='object')?[v]:[]);if(Array.isArray(x?.result?.list))return x.result.list;if(Array.isArray(x?.list))return x.list;return []}
function first(o,ks){for(const k of ks){const v=n(o?.[k]);if(ok(v))return v}return NaN}
function normalized(source,id,name,stats={}){return{source,venue:VENUES[source]?.label||source,traderId:String(id),name:name||String(id),stats:{trades7d:first(stats,['trades7d']),activeDays:first(stats,['activeDays']),wr:first(stats,['wr']),pf:first(stats,['pf']),pnl7d:first(stats,['pnl7d']),dd:first(stats,['dd']),avgHoldH:first(stats,['avgHoldH']),medianHoldH:first(stats,['medianHoldH']),roi7d:first(stats,['roi7d']),aum:first(stats,['aum']),daysTrading:first(stats,['daysTrading'])},coverage:stats.coverage||'UNKNOWN',discoveredAt:Date.now()}}
function activityPerDay(t){const s=t.stats;return ok(s.trades7d)&&ok(s.activeDays)&&s.activeDays>0?s.trades7d/s.activeDays:NaN}
function qualityGate(t){const s=t.stats,r=[];const daily=activityPerDay(t);if(!ok(s.trades7d)||s.trades7d<MIN_TRADES)r.push(`TRADES_7D<${MIN_TRADES}`);if(!ok(s.activeDays)||s.activeDays<MIN_DAYS)r.push(`ACTIVE_DAYS<${MIN_DAYS}`);if(!ok(daily)||daily<MIN_DAILY_TRADES)r.push(`DAILY_TRADES<${MIN_DAILY_TRADES}`);if(!ok(s.wr)||s.wr<MIN_WR)r.push(`WR<${MIN_WR}%`);if(!ok(s.pf)||s.pf<MIN_PF)r.push(`PF<${MIN_PF}`);if(ok(s.medianHoldH)&&s.medianHoldH>MAX_MEDIAN_H)r.push(`MEDIAN_HOLD>${MAX_MEDIAN_H}H`);if(ok(s.avgHoldH)&&s.avgHoldH>MAX_AVG_H)r.push(`AVG_HOLD>${MAX_AVG_H}H`);if(ok(s.dd)&&s.dd>MAX_DD)r.push(`DD>${MAX_DD}%`);return r}
function qualityScore(t){const s=t.stats,d=activityPerDay(t);let q=0;q+=ok(s.wr)?Math.max(0,Math.min(30,(s.wr-50)*0.9)):0;q+=ok(s.pf)?Math.min(s.pf,5)*6:0;q+=ok(d)?Math.min(d,30)*1.1:0;q+=ok(s.activeDays)?Math.min(s.activeDays,7)*2:0;q+=ok(s.pnl7d)?Math.max(-10,Math.min(10,s.pnl7d/2000)):0;q-=ok(s.dd)?Math.min(s.dd,40)*0.7:15;q-=ok(s.medianHoldH)?Math.min(s.medianHoldH,12)*0.7:0;return q}
function signalScore(t){const s=t.stats,p=t.position;let q=qualityScore(t);if(p){q+=ok(p.distancePct)?Math.max(0,12-Math.abs(p.distancePct)*12):0;q+=ok(p.openedAt)?Math.max(0,10-(Date.now()-p.openedAt)/60000/2):0;}return q}
function positionGate(t){const p=t.position;if(!p)return['NO_CURRENT_POSITION'];const r=[];const age=(Date.now()-n(p.openedAt))/60000;if(!ok(age)||age>FRESH_MIN)r.push(`STALE>${FRESH_MIN}M`);if(!ok(p.entry)||!ok(p.mark)||p.entry<=0)r.push('NO_ENTRY_MARK');else{p.distancePct=(p.mark-p.entry)/p.entry*100*(p.side==='SHORT'?-1:1);if(Math.abs(p.distancePct)>ENTRY_MAX)r.push(`ENTRY_DISTANCE>${ENTRY_MAX}%`)}if(!['LONG','SHORT'].includes(p.side))r.push('SIDE_UNKNOWN');const risk=p.entry*MODEL_SL_PCT/100;const reward=risk*MODEL_TP_R;p.sl=p.side==='LONG'?p.entry-risk:p.entry+risk;p.tp=p.side==='LONG'?p.entry+reward:p.entry-reward;p.rr=MODEL_TP_R;return r}
async function withTimeout(p,ms,label){let timer;try{return await Promise.race([p,new Promise((_,rej)=>timer=setTimeout(()=>rej(new Error(`TIMEOUT:${label}:${ms}ms`)),ms))])}finally{clearTimeout(timer)}}
async function mapBounded(items,limit,worker){const out=new Array(items.length);let cursor=0;const nw=Math.max(1,Math.min(limit,items.length));await Promise.all(Array.from({length:nw},async()=>{while(true){const i=cursor++;if(i>=items.length)break;try{out[i]=await worker(items[i],i)}catch(e){out[i]={...items[i],coverage:'VERIFY_ERROR',verifyError:String(e.message||e)}}}}));return out.filter(Boolean)}

async function hyperliquid(){const status={source:'HYPERLIQUID',class:'FULL_SIGNAL',state:'UNAVAILABLE',discovered:0,error:null};const out=[];try{const rows=arr(await json('https://stats-data.hyperliquid.xyz/Mainnet/leaderboard'));for(const x of rows.slice(0,DISCOVERY_LIMIT)){const id=x?.ethAddress||x?.address;if(!id)continue;const perf=new Map((x?.windowPerformances||[]).map(v=>[v?.[0],v?.[1]]));const w=perf.get('week')||{};out.push(normalized('HYPERLIQUID',id,x?.displayName||id,{pnl7d:n(w.pnl),roi7d:n(w.roi)*100,aum:n(x?.accountValue)}))}status.discovered=out.length;status.state=out.length?'OK':'EMPTY';return{status,out}}catch(e){status.error=String(e.message||e);return{status,out}}}
function hlStats(fills){const c=fills.filter(f=>ok(f.closedPnl)&&Math.abs(n(f.closedPnl))>0),wins=c.filter(f=>n(f.closedPnl)>0),loss=c.filter(f=>n(f.closedPnl)<0),gp=wins.reduce((a,f)=>a+n(f.closedPnl),0),gl=Math.abs(loss.reduce((a,f)=>a+n(f.closedPnl),0)),days=new Set(c.map(f=>new Date(f.time).toISOString().slice(0,10))),holds=[],q=new Map();for(const f of [...fills].sort((a,b)=>a.time-b.time)){const side=String(f.dir||'').toUpperCase().includes('SELL')?'SHORT':'LONG',key=f.coin+'|'+side;if(!q.has(key))q.set(key,[]);if(!ok(f.closedPnl)||Math.abs(n(f.closedPnl))<1e-12)q.get(key).push(f.time);else{const o=q.get(key).shift();if(ok(o))holds.push((f.time-o)/3600000)}}const sh=holds.sort((a,b)=>a-b);let eq=0,peak=0,dd=0;for(const f of c){eq+=n(f.closedPnl);peak=Math.max(peak,eq);if(peak>0)dd=Math.max(dd,(peak-eq)/peak*100)}return{trades7d:c.length,activeDays:days.size,wr:c.length?wins.length/c.length*100:NaN,pf:gl?gp/gl:(gp>0?Infinity:NaN),avgHoldH:holds.length?holds.reduce((a,b)=>a+b,0)/holds.length:NaN,medianHoldH:sh.length?sh[Math.floor(sh.length/2)]:NaN,dd}}
async function hlVerify(t){try{return await withTimeout(hlVerifyInner(t),VERIFY_TIMEOUT_MS,'HL')}catch(e){t.coverage='VERIFY_ERROR';t.verifyError='HL:'+String(e.message||e);return t}}
async function hlVerifyInner(t){const end=Date.now(),start=end-LOOKBACK_MS;const fills=await postJson('https://api.hyperliquid.xyz/info',{type:'userFillsByTime',user:t.traderId,startTime:start,endTime:end});const fs=Array.isArray(fills)?fills:[];if(!fs.length){t.coverage='VERIFY_EMPTY';t.verifyError='HL_NO_FILLS_7D';t.stats={...t.stats,trades7d:0,activeDays:0};return t}t.stats={...t.stats,...hlStats(fs)};t.coverage='COMPLETE';t.audit={fills7d:fs.length,verifiedAt:Date.now()};if(qualityGate(t).length===0){const state=await postJson('https://api.hyperliquid.xyz/info',{type:'clearinghouseState',user:t.traderId});const positions=(state?.assetPositions||[]).map(x=>x?.position).filter(Boolean);let best=null;for(const p of positions){const sz=n(p?.szi);if(!sz)continue;const side=sz>0?'LONG':'SHORT',symbol=p?.coin||'',entry=n(p?.entryPx),mark=n(p?.markPx);if(!ok(entry)||!ok(mark)||!symbol)continue;const recent=fs.filter(f=>f?.coin===symbol).sort((a,b)=>n(b?.time)-n(a?.time));const last=recent[0];best={symbol,side,entry,mark,size:Math.abs(sz),openedAt:n(last?.time,n(p?.timestamp,Date.now())),lastActivityAt:n(last?.time,n(p?.timestamp,Date.now())),source:'HYPERLIQUID'};break}if(best)t.position=best;t.audit.currentPositions=positions.length}return t}

async function binance(){const status={source:'BINANCE',class:'DISCOVERY',state:'UNAVAILABLE',discovered:0,error:null};const out=new Map();const url='https://www.binance.com/bapi/futures/v1/friendly/future/copy-trade/home-page/query-list';try{for(const dataType of ['ROI','PNL','MDD']){const x=await postJson(url,{pageNumber:1,pageSize:100,timeRange:'90D',dataType,favoriteOnly:false,hideFull:false,nickname:'',order:'DESC',apiKeyOnly:false});for(const r of arr(x)){const id=r?.leadPortfolioId||r?.portfolioId;if(!id)continue;out.set(String(id),normalized('BINANCE',id,r?.nickname||r?.nickName||id,{trades7d:first(r,['tradeCount7d','tradeCount7dTotal']),activeDays:first(r,['activeDays','daysTrading']),wr:first(r,['winRate']),pf:first(r,['profitFactor']),pnl7d:first(r,['pnl7d','pnl']),dd:first(r,['mdd','maxDrawdown','maxDrawdownRate']),roi7d:first(r,['roi7d','roi']),aum:first(r,['aum','totalAssets']),coverage:'PARTIAL'}))}if(out.size>=DISCOVERY_LIMIT)break}const list=[...out.values()].slice(0,DISCOVERY_LIMIT);status.discovered=list.length;status.state=list.length?'OK':'EMPTY';if(!list.length)status.error='BINANCE_NO_PUBLIC_PORTFOLIOS';return{status,out:list}}catch(e){status.error='BINANCE:'+String(e.message||e);return{status,out:[]}}}
function parseEmbedded(html,source){const found=new Map(),patterns=source==='BYBIT'?[/(?:uid|userId|masterTraderId)"?\s*:\s*"?([A-Za-z0-9_-]{5,})/g]:[/(?:traderId|uid|userId|projectId)"?\s*:\s*"?([A-Za-z0-9_-]{5,})/g];for(const re of patterns){let m;while((m=re.exec(html))){const id=m[1],chunk=html.slice(Math.max(0,m.index-1200),Math.min(html.length,m.index+2500));const name=(chunk.match(/"(?:nickName|nickname|traderName|displayName)"\s*:\s*"([^"]+)/)||[])[1]||id;found.set(id,normalized(source,id,name,{}))}}return[...found.values()]}
async function webDiscovery(source,url){const status={source,class:'DISCOVERY',state:'UNAVAILABLE',discovered:0,error:null};try{const html=await fetchTextRetry(url,{},'GEN');const out=parseEmbedded(html,source).slice(0,DISCOVERY_LIMIT);status.discovered=out.length;status.state=out.length?'OK':'EMPTY';if(!out.length)status.error='PUBLIC_PAGE_NO_MACHINE_READABLE_TRADER_IDS';return{status,out}}catch(e){status.error=String(e.message||e);return{status,out:[]}}}
async function bybit(){return webDiscovery('BYBIT','https://www.bybit.com/copyTrading/en/leader-board')} async function bitget(){return webDiscovery('BITGET','https://www.bitget.com/copy-trading/futures')}

// OKX is intentionally discovery-only in V1.8. OKX documents public lead-trader
// profile metrics, but the current public machine-readable position endpoints
// are not treated as verified by this worker. We never infer a live signal from
// an unverified page/API response.
async function okx(){const status={source:'OKX',class:'DISCOVERY',state:'UNAVAILABLE',discovered:0,error:null},seen=new Map();const bases=['https://eea.okx.com','https://openapi.okx.com'];let lastErr='';try{for(const base of bases){try{for(const sortType of ['overview','pnl','aum','win_ratio']){for(let page=1;page<=4;page++){const u=`${base}/api/v5/copytrading/public-lead-traders?instType=SWAP&sortType=${sortType}&state=0&minLeadDays=1&page=${page}&limit=20`;const x=await json(u);for(const r of arr(x)){const id=r?.uniqueCode||r?.traderId||r?.uid;if(!id)continue;const wrRaw=first(r,['winRatio','winRate','winRatePct']);seen.set(String(id),normalized('OKX',id,r?.nickName||r?.nickNameEn||r?.displayName||id,{wr:ok(wrRaw)?(wrRaw<=1?wrRaw*100:wrRaw):NaN,pnl7d:first(r,['pnl','pnl7d','profit']),roi7d:first(r,['pnlRatio','roi','roi7d']),aum:first(r,['aum','aumValue']),daysTrading:first(r,['leadDays','daysTrading']),activeDays:first(r,['leadDays','daysTrading']),coverage:'DISCOVERY_ONLY'}))}if(seen.size>=DISCOVERY_LIMIT)break}if(seen.size>=DISCOVERY_LIMIT)break}if(seen.size)break}catch(e){lastErr=String(e.message||e)}}const out=[...seen.values()].slice(0,DISCOVERY_LIMIT);status.discovered=out.length;status.state=out.length?'OK':'EMPTY';if(!out.length)status.error=lastErr?`OKX:${lastErr}`:'OKX_NO_PUBLIC_LEAD_TRADERS';return{status,out}}catch(e){status.error='OKX:'+String(e.message||e);return{status,out:[]}}}

async function cacheLoad(){const c=await readJson(CACHE_FILE,{sources:{}});return c?.sources||{}}
async function cacheSave(sources){await writeJson(CACHE_FILE,{version:VERSION,generatedAt:Date.now(),sources})}
async function withCache(result,cache){const s=result.status;if(result.out.length){cache[s.source]={savedAt:Date.now(),items:result.out};return result}const old=cache[s.source];if(old?.items?.length&&(Date.now()-n(old.savedAt))/3600000<=CACHE_TTL_H){s.state='CACHE';s.error=(s.error?s.error+' | ':'')+'USING_LAST_GOOD_DISCOVERY';return{status:s,out:old.items.map(x=>({...x,fromCache:true}))}}return result}
async function unsupported(source){return{status:{source,class:'UNSUPPORTED',state:'UNSUPPORTED',discovered:0,error:'NO_VERIFIED_PUBLIC_READ_ONLY_TRADER_DISCOVERY'},out:[]}}
async function telegram(text){if(!TELEGRAM_TOKEN||!TELEGRAM_CHAT_ID){console.log('[TELEGRAM] skipped: missing credentials');return}try{const raw=await fetchTextRetry(`https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:TELEGRAM_CHAT_ID,text,disable_web_page_preview:true})},'GEN');const x=JSON.parse(raw);if(!x.ok)throw new Error(`TELEGRAM_API:${x.error_code||''}:${x.description||'unknown'}`);console.log('[TELEGRAM] sent')}catch(e){console.log('[TELEGRAM]',e.message)}}
function report(statuses,all,audited,signals,blocked,runtime,stats){return reportV19(statuses,all,[],audited,signals,blocked,runtime,stats)}
function reportV19(statuses,all,watch,audited,signals,blocked,runtime,stats){const full=statuses.filter(s=>s.class==='FULL_SIGNAL'&&['OK','CACHE'].includes(s.state)).length,disc=statuses.filter(s=>s.class==='DISCOVERY'&&['OK','CACHE'].includes(s.state)).length,uns=statuses.filter(s=>s.state==='UNSUPPORTED').length;const cov={COMPLETE:audited.filter(t=>t.coverage==='COMPLETE').length,EMPTY:audited.filter(t=>t.coverage==='VERIFY_EMPTY').length,ERROR:audited.filter(t=>t.coverage==='VERIFY_ERROR').length};const L=[`🌐 GLOBAL FUTURES ACTIVE-TRADER HUNTER`,`🧠 ${VERSION}`,`📡 READ-ONLY | NO ORDERS | NO AUTO-COPY | FUTURES ONLY`,`━━━━━━━━━━━━━━━━━━`,`🔎 Full-signal sources: ${full}/${statuses.length} | Discovery sources: ${disc}/${statuses.length} | Unsupported: ${uns}/${statuses.length}`,`👥 Global traders discovered: ${all.length} | HL audit candidates: ${stats.hlCandidates} | Audited: ${audited.length} | Actionable: ${signals.length}/${TOP_SIGNALS}`,`🎯 QUALITY: 7D trades≥${MIN_TRADES} | active days≥${MIN_DAYS} | avg/day≥${MIN_DAILY_TRADES} | WR≥${MIN_WR}% | PF≥${MIN_PF} | median≤${MAX_MEDIAN_H}h | avg≤${MAX_AVG_H}h | DD≤${MAX_DD}%`,`⚡ SIGNAL: fresh≤${FRESH_MIN}m | entry≤${ENTRY_MAX}% | RR≥${MIN_RR} | model SL=${MODEL_SL_PCT}% | TP=${MODEL_TP_R}R`,`⏱ Runtime: ${runtime.toFixed(1)}s`,'','📡 SOURCE STATUS'];for(const s of statuses)L.push(`${s.source}: ${s.state} | ${s.class} | discovered=${s.discovered}${s.error?' | '+s.error.slice(0,110):''}`);L.push(`🧾 HL audit: complete=${cov.COMPLETE} | empty=${cov.EMPTY} | error=${cov.ERROR} | quality-pass=${stats.qualityPass} | positions-checked=${stats.positionChecked}`,'','👑 GLOBAL FOLLOW WATCHLIST');if(watch.length){for(const t of watch.slice(0,12)){const s=t.stats,d=activityPerDay(t);L.push(`${t.venue} ${trunc(t.name,20)} | WR ${pct(s.wr,1)} | 7D ${ok(s.trades7d)?s.trades7d:'—'} trades | ${ok(d)?d.toFixed(1):'—'}/day | PF ${ok(s.pf)?s.pf.toFixed(2):'—'} | DD ${pct(s.dd,1)}`)}}else L.push('No verified global watchlist candidates.');L.push('','🔥 ACTIONABLE NOW');if(!signals.length)L.push('No trader passed BOTH the low-error/high-activity quality gate and current-position gate this cycle.');else signals.forEach((t,i)=>{const p=t.position,s=t.stats,d=activityPerDay(t);L.push(`${i+1}. ${t.venue} ${trunc(t.name)} | ${p.side} ${p.symbol} | Entry ${p.entry} | Now ${p.mark} | Dist ${pct(p.distancePct)} | RR ${p.rr.toFixed(2)} | Age ${((Date.now()-p.openedAt)/60000).toFixed(1)}m | WR ${pct(s.wr,1)} | ${d.toFixed(1)}/day | PF ${s.pf.toFixed(2)} | Score ${signalScore(t).toFixed(1)}`)});L.push('','🧱 TOP BLOCKED / WHY');blocked.slice(0,12).forEach(t=>L.push(`${t.venue} ${trunc(t.name,22)}: ${t.reasons.join(' | ')}`));L.push('','ℹ️ Global discovery is retained even when a venue cannot expose a verified public live position. Such traders stay on the watchlist, not in actionable signals.');return L.join('\n')}
async function main(){const started=Date.now();await ensure();console.log(`GFTSH ${VERSION} | READ-ONLY | FUTURES ONLY`);const cache=await cacheLoad();const fns=[hyperliquid,binance,okx,bybit,bitget,()=>unsupported('KUCOIN'),()=>unsupported('GATE'),()=>unsupported('MEXC'),()=>unsupported('PHEMEX'),()=>unsupported('BINGX'),()=>unsupported('COINEX'),()=>unsupported('DYDX'),()=>unsupported('PARADEX')];const results=[];for(const fn of fns){let r;try{r=await fn()}catch(e){r={status:{source:'UNKNOWN',class:'DISCOVERY',state:'UNAVAILABLE',discovered:0,error:String(e.message||e)},out:[]}}results.push(await withCache(r,cache));await sleep(30)}await cacheSave(Object.fromEntries(results.map(r=>[r.status.source,{savedAt:Date.now(),items:r.out}])));const statuses=results.map(r=>r.status);const map=new Map();for(const r of results)for(const t of r.out){const k=`${t.source}:${t.traderId}`;if(!map.has(k))map.set(k,t)}const all=[...map.values()];const hl=[...all.filter(t=>t.source==='HYPERLIQUID')].sort((a,b)=>qualityScore(b)-qualityScore(a));const hlPool=hl.slice(0,HL_AUDIT_LIMIT);const audited=await mapBounded(hlPool,VERIFY_CONCURRENCY,hlVerify);let qualityPass=0,positionChecked=0,hlErrors=0;for(const t of audited){t.gate=qualityGate(t);if(t.coverage==='VERIFY_ERROR')hlErrors++;if(!t.gate.length){qualityPass++;const pg=positionGate(t);t.signalGate=pg;if(t.position)positionChecked++}}const signals=audited.filter(t=>t.gate.length===0&&t.signalGate?.length===0);signals.sort((a,b)=>qualityScore(b)-qualityScore(a));const blocked=audited.filter(t=>t.gate.length||t.signalGate?.length).map(t=>({venue:t.venue,name:t.name,reasons:[...t.gate,...(t.gate.length?[]:t.signalGate)]}));const text=report(statuses,all,audited,signals.slice(0,TOP_SIGNALS),blocked,(Date.now()-started)/1000,{hlCandidates:hlPool.length,hlErrors,qualityPass,positionChecked});console.log(text);await writeJson(STATE_FILE,{version:VERSION,updatedAt:Date.now(),statuses,discovered:all.length,hlAuditCandidates:hlPool.length,audited:audited.length,qualityPass,positionChecked,signals:signals.length,top:signals.slice(0,TOP_SIGNALS)});await telegram(text)}
main().catch(e=>{console.error('[FATAL]',e);process.exitCode=1});
